-- Priority 15 trivia rewrite
-- Generated by Codex on 2026-06-01 for Claude Code review/application.
-- Rules followed: no person names, plausible same-domain distractors, no deletes.

-- ---------------------------------------------------------------------------
-- BA: Boeing
-- ---------------------------------------------------------------------------

UPDATE trivia_questions
SET option_a = 'defense and space',
    option_b = 'commercial services',
    option_c = 'aircraft leasing',
    option_d = 'industrial systems',
    correct_answer = 'a',
    fun_fact = 'Not just passenger jets. Defense work is always in the hangar.'
WHERE company_id = 'ba'
  AND question = 'Besides commercial airplanes, what is its other major segment?';

UPDATE trivia_questions
SET option_a = 'defense',
    option_b = 'space launch',
    option_c = 'civil aviation',
    option_d = 'public transit',
    correct_answer = 'a',
    fun_fact = 'The customer is often a government. Different sales cycle, same giant machines.'
WHERE company_id = 'ba'
  AND question = 'The company is a major contractor for which sector?';

UPDATE trivia_questions
SET option_a = 'the s&p 500',
    option_b = 'the russell 2000',
    option_c = 'the dow 30',
    option_d = 'no major index',
    correct_answer = 'c',
    fun_fact = 'Big industrial name, big index spotlight.'
WHERE company_id = 'ba'
  AND question = 'The company is a component of which index?';

UPDATE trivia_questions
SET fun_fact = COALESCE(fun_fact, 'Aerospace trivia: big numbers, long cycles, no small stakes.')
WHERE company_id = 'ba'
  AND fun_fact IS NULL;

-- ---------------------------------------------------------------------------
-- KO: Coca-Cola
-- ---------------------------------------------------------------------------

UPDATE trivia_questions
SET option_a = '7up',
    option_b = 'sprite',
    option_c = 'mountain dew',
    option_d = 'sierra mist',
    correct_answer = 'b',
    fun_fact = 'The clear soda has the green-bottle energy. Very on brand.'
WHERE company_id = 'ko'
  AND question = 'Which lemon-lime soft drink does the company own?';

UPDATE trivia_questions
SET option_a = 'gatorade',
    option_b = 'propel',
    option_c = 'powerade',
    option_d = 'bodyarmor',
    correct_answer = 'c',
    fun_fact = 'The sports drink lane has rivals. This one wears the red label.'
WHERE company_id = 'ko'
  AND question = 'Which sports-drink brand does the company control?';

UPDATE trivia_questions
SET option_a = 'the russell 2000',
    option_b = 'the dow 30',
    option_c = 'the nasdaq 100',
    option_d = 'no major index',
    correct_answer = 'b',
    fun_fact = 'A classic consumer staple, right where old-school index watchers expect it.'
WHERE company_id = 'ko'
  AND question = 'The company is a component of which index?';

UPDATE trivia_questions
SET option_a = 'perrier',
    option_b = 'evian',
    option_c = 'aquafina',
    option_d = 'dasani',
    correct_answer = 'd',
    fun_fact = 'Water too. The cooler door is more crowded than it looks.'
WHERE company_id = 'ko'
  AND question = 'Which bottled water brand does the company own?';

UPDATE trivia_questions
SET fun_fact = COALESCE(fun_fact, 'The portfolio is bigger than the red can.')
WHERE company_id = 'ko'
  AND fun_fact IS NULL;

-- ---------------------------------------------------------------------------
-- MMM: 3M
-- ---------------------------------------------------------------------------

UPDATE trivia_questions
SET option_a = 'rubber goods',
    option_b = 'mining and abrasives',
    option_c = 'industrial chemicals',
    option_d = 'paper products',
    correct_answer = 'b',
    fun_fact = 'The name started in the ground. The portfolio got much stickier later.'
WHERE company_id = 'mmm'
  AND question = 'The company began in which original line of business?';

UPDATE trivia_questions
SET option_a = 'duck',
    option_b = 'gorilla',
    option_c = 'scotch',
    option_d = 'tesa',
    correct_answer = 'c',
    fun_fact = 'A tape brand so familiar it almost became the category.'
WHERE company_id = 'mmm'
  AND question = 'Which transparent tape brand belongs to the company?';

UPDATE trivia_questions
SET option_a = 'band-aid',
    option_b = 'nexcare',
    option_c = 'curad',
    option_d = 'tegaderm',
    correct_answer = 'b',
    fun_fact = 'Small bandage aisle, big brand memory.'
WHERE company_id = 'mmm'
  AND question = 'Which health-care brand belongs to the company?';

UPDATE trivia_questions
SET option_a = 'the dow 30',
    option_b = 'no major index',
    option_c = 'the russell 2000',
    option_d = 'the s&p 500',
    correct_answer = 'd',
    fun_fact = 'Still a major large-cap name, just not in every famous basket.'
WHERE company_id = 'mmm'
  AND question = 'The company is a component of which index?';

UPDATE trivia_questions
SET fun_fact = COALESCE(fun_fact, 'Many products, one ticker that says it three times.')
WHERE company_id = 'mmm'
  AND fun_fact IS NULL;

-- ---------------------------------------------------------------------------
-- CAT: Caterpillar
-- ---------------------------------------------------------------------------

UPDATE trivia_questions
SET option_a = 'service contract model',
    option_b = 'distribution network',
    option_c = 'government sales desk',
    option_d = 'factory automation plan',
    correct_answer = 'b',
    fun_fact = 'The dealer network is part of the moat. Yellow iron needs local muscle.'
WHERE company_id = 'cat'
  AND question = 'Independent dealers are a key part of the company''s what?';

UPDATE trivia_questions
SET option_a = 'healthcare and labs',
    option_b = 'financial services',
    option_c = 'construction and mining',
    option_d = 'consumer retail',
    correct_answer = 'c',
    fun_fact = 'If the job site is huge and dusty, this name may be nearby.'
WHERE company_id = 'cat'
  AND question = 'The company''s products are commonly used in which sectors?';

UPDATE trivia_questions
SET option_a = 'energy and transportation',
    option_b = 'resource industries',
    option_c = 'financial products',
    option_d = 'services',
    correct_answer = 'b',
    fun_fact = 'Digging and hauling: the phrase practically points to the segment.'
WHERE company_id = 'cat'
  AND question = 'Digging and hauling machinery falls under which segment theme?';

UPDATE trivia_questions
SET option_a = 'illinois',
    option_b = 'ohio',
    option_c = 'nevada',
    option_d = 'texas',
    correct_answer = 'd',
    fun_fact = 'The headquarters moved. The machines stayed unmistakably yellow.'
WHERE company_id = 'cat'
  AND question = 'The company is headquartered in which state?';

UPDATE trivia_questions
SET fun_fact = COALESCE(fun_fact, 'Heavy equipment trivia. Bring a hard hat.')
WHERE company_id = 'cat'
  AND fun_fact IS NULL;

-- ---------------------------------------------------------------------------
-- JPM: JPMorgan Chase
-- ---------------------------------------------------------------------------

UPDATE trivia_questions
SET option_a = 'an investment firm',
    option_b = 'a bank',
    option_c = 'a commercial lender',
    option_d = 'a credit union',
    correct_answer = 'b',
    fun_fact = 'Huge balance sheet, many businesses, still a bank at the center.'
WHERE company_id = 'jpm'
  AND question = 'The company is primarily what type of business?';

UPDATE trivia_questions
SET option_a = 'market value',
    option_b = 'branch count',
    option_c = 'assets',
    option_d = 'employee count',
    correct_answer = 'c',
    fun_fact = 'For banks, assets are the scoreboard everyone quotes.'
WHERE company_id = 'jpm'
  AND question = 'It is often cited as the largest US bank by what measure?';

UPDATE trivia_questions
SET option_a = 'the nasdaq 100',
    option_b = 'the s&p smallcap 600',
    option_c = 'no major index',
    option_d = 'the dow 30',
    correct_answer = 'd',
    fun_fact = 'Old-school blue chip energy, with a very modern balance sheet.'
WHERE company_id = 'jpm'
  AND question = 'The company is a component of which index?';

UPDATE trivia_questions
SET option_a = 'consumer and community banking',
    option_b = 'custody services',
    option_c = 'insurance underwriting',
    option_d = 'commercial real estate',
    correct_answer = 'a',
    fun_fact = 'Cards, branches, deposits. The everyday side of a giant bank.'
WHERE company_id = 'jpm'
  AND question = 'Which is one of the company''s business segments?';

UPDATE trivia_questions
SET option_a = 'treasury services',
    option_b = 'the corporate and investment bank',
    option_c = 'consumer lending',
    option_d = 'wealth advisory',
    correct_answer = 'b',
    fun_fact = 'Deal fees live where the bankers do their banker things.'
WHERE company_id = 'jpm'
  AND question = 'Investment-banking fees sit within which broad activity?';

UPDATE trivia_questions
SET option_a = 'chicago',
    option_b = 'denver',
    option_c = 'new york city',
    option_d = 'miami',
    correct_answer = 'c',
    fun_fact = 'The headquarters answer is very finance-core.'
WHERE company_id = 'jpm'
  AND question = 'The company is headquartered in which city?';

UPDATE trivia_questions
SET option_a = 'commercial banking',
    option_b = 'consumer banking',
    option_c = 'payments',
    option_d = 'asset and wealth management',
    correct_answer = 'd',
    fun_fact = 'Money management is a segment, not a side quest.'
WHERE company_id = 'jpm'
  AND question = 'Wealth management falls under which segment?';

UPDATE trivia_questions
SET option_a = 'potential loan losses',
    option_b = 'branch renovations',
    option_c = 'trading software',
    option_d = 'customer rewards',
    correct_answer = 'a',
    fun_fact = 'A reserve build is the bank saying: maybe some loans get rough.'
WHERE company_id = 'jpm'
  AND question = 'A bank ''reserve build'' sets aside money for what?';

UPDATE trivia_questions
SET option_a = 'insurance claims',
    option_b = 'lending and deposits',
    option_c = 'real estate brokerage',
    option_d = 'payroll software',
    correct_answer = 'b',
    fun_fact = 'The basics still matter, even at giant-bank scale.'
WHERE company_id = 'jpm'
  AND question = 'Which is a core banking activity for the company?';

UPDATE trivia_questions
SET option_a = 'only governments',
    option_b = 'only small businesses',
    option_c = 'consumers and corporations',
    option_d = 'only asset managers',
    correct_answer = 'c',
    fun_fact = 'The client list is basically the economy.'
WHERE company_id = 'jpm'
  AND question = 'The company serves which broad customer base?';

UPDATE trivia_questions
SET fun_fact = COALESCE(fun_fact, 'Bank trivia: less sparkle, more balance sheet.')
WHERE company_id = 'jpm'
  AND fun_fact IS NULL;

-- ---------------------------------------------------------------------------
-- MRK: Merck
-- ---------------------------------------------------------------------------

UPDATE trivia_questions
SET option_a = 'medical devices',
    option_b = 'pharmaceuticals',
    option_c = 'diagnostics',
    option_d = 'biotech tools',
    correct_answer = 'b',
    fun_fact = 'This is the medicine lane, not the device shelf.'
WHERE company_id = 'mrk'
  AND question = 'The company primarily operates in which industry?';

UPDATE trivia_questions
SET option_a = 'medical devices',
    option_b = 'hospital equipment',
    option_c = 'prescription medicines and vaccines',
    option_d = 'over-the-counter supplements',
    correct_answer = 'c',
    fun_fact = 'Pills, vaccines, and pipelines. That is the core vocabulary.'
WHERE company_id = 'mrk'
  AND question = 'The company''s products are mainly what?';

UPDATE trivia_questions
SET option_a = 'the kidneys',
    option_b = 'the liver',
    option_c = 'the digestive tract',
    option_d = 'the lungs and heart',
    correct_answer = 'd',
    fun_fact = 'The name sounds technical because the disease is very specific.'
WHERE company_id = 'mrk'
  AND question = '''Pulmonary arterial'' hypertension chiefly affects which system?';

UPDATE trivia_questions
SET option_a = 'the russell 2000',
    option_b = 'the dow 30',
    option_c = 'the nasdaq 100',
    option_d = 'no major index',
    correct_answer = 'b',
    fun_fact = 'A pharma heavyweight with blue-chip credentials.'
WHERE company_id = 'mrk'
  AND question = 'The company is a component of which index?';

UPDATE trivia_questions
SET fun_fact = COALESCE(fun_fact, 'Pharma trivia: one blockbuster can carry a lot of airtime.')
WHERE company_id = 'mrk'
  AND fun_fact IS NULL;

-- ---------------------------------------------------------------------------
-- SHW: Sherwin-Williams
-- ---------------------------------------------------------------------------

UPDATE trivia_questions
SET option_a = 'big-box home improvement stores',
    option_b = 'independent paint dealers',
    option_c = 'online direct',
    option_d = 'its own stores',
    correct_answer = 'd',
    fun_fact = 'The store network is the strategy. Paint has a storefront.'
WHERE company_id = 'shw'
  AND question = 'Professional paint is sold largely through what channel?';

UPDATE trivia_questions
SET option_a = 'consumer brands group',
    option_b = 'paint stores group',
    option_c = 'performance coatings',
    option_d = 'the americas segment',
    correct_answer = 'c',
    fun_fact = 'Factories need coatings too. Not every can goes on a living-room wall.'
WHERE company_id = 'shw'
  AND question = 'Which segment serves manufacturers and industrial uses?';

UPDATE trivia_questions
SET option_a = 'architectural and industrial coating',
    option_b = 'automotive refinishing',
    option_c = 'household cleaning',
    option_d = 'industrial adhesives',
    correct_answer = 'a',
    fun_fact = 'The category sounds dull until every surface needs a finish.'
WHERE company_id = 'shw'
  AND question = 'The company''s products are mainly used for what?';

UPDATE trivia_questions
SET option_a = 'the dow 30',
    option_b = 'the s&p 500',
    option_c = 'the russell microcap',
    option_d = 'no major index',
    correct_answer = 'b',
    fun_fact = 'Not just a paint store name. It is a major market name.'
WHERE company_id = 'shw'
  AND question = 'The company is a component of which index?';

UPDATE trivia_questions
SET fun_fact = COALESCE(fun_fact, 'Paint trivia. More strategic than watching it dry.')
WHERE company_id = 'shw'
  AND fun_fact IS NULL;

-- ---------------------------------------------------------------------------
-- NKE: Nike existing rows
-- ---------------------------------------------------------------------------

UPDATE trivia_questions
SET question = 'What was the company''s early business model before becoming its own brand?',
    option_a = 'licensing apparel designs',
    option_b = 'importing and distributing shoes',
    option_c = 'running factory stores',
    option_d = 'owning domestic factories',
    correct_answer = 'b',
    fun_fact = 'Before the brand became the brand, distribution did the heavy lifting.'
WHERE company_id = 'nke'
  AND question = 'What was the primary business model before the company shifted to outsourced manufacturing?';

UPDATE trivia_questions
SET question = 'Which brand did the company acquire in 2003?',
    option_a = 'reebok',
    option_b = 'converse',
    option_c = 'vans',
    option_d = 'puma',
    correct_answer = 'b',
    fun_fact = 'A classic sneaker name joined the portfolio.'
WHERE company_id = 'nke'
  AND question = 'In what year did the company acquire the Converse brand?';

UPDATE trivia_questions
SET fun_fact = COALESCE(fun_fact, 'Brand trivia with a swoosh-shaped shadow.')
WHERE company_id = 'nke'
  AND fun_fact IS NULL;

INSERT INTO trivia_questions
  (company_id, question, option_a, option_b, option_c, option_d,
   correct_answer, category, difficulty, is_active, fun_fact)
VALUES
  ('nke', 'What is the company''s stock ticker?', 'nke', 'nik', 'nki', 'nka', 'a', 'earnings', 'easy', true, 'Three letters. Everybody knows the logo.'),
  ('nke', 'Which sales channel sells directly to consumers?', 'wholesale partners', 'licensees', 'nike direct', 'franchise stores', 'c', 'earnings', 'medium', true, 'When the company says direct, it means keeping the customer close.'),
  ('nke', 'Which geography is one of the company''s key reported regions?', 'greater china', 'the nordics', 'the gulf region', 'central africa', 'a', 'earnings', 'medium', true, 'That region gets its own spotlight on calls.'),
  ('nke', 'Which product category is the brand best known for?', 'sporting footwear', 'home appliances', 'cloud software', 'hotel lodging', 'a', 'earnings', 'easy', true, 'Start with the shoes. Everything else follows.'),
  ('nke', 'What month ends the company''s fiscal year?', 'december', 'march', 'may', 'september', 'c', 'earnings', 'hard', true, 'A fiscal calendar wrinkle. Not every year ends in december.'),
  ('nke', 'What does currency-neutral revenue exclude?', 'exchange-rate changes', 'wholesale orders', 'factory output', 'store openings', 'a', 'earnings', 'medium', true, 'Global brands need a cleaner currency lens.');

-- ---------------------------------------------------------------------------
-- WMT: Walmart
-- ---------------------------------------------------------------------------

UPDATE trivia_questions
SET option_a = '1991',
    option_b = '1995',
    option_c = '1988',
    option_d = '1999',
    correct_answer = 'a',
    fun_fact = 'The first international step came just across the border.'
WHERE company_id = 'wmt'
  AND question = 'What year did the company expand internationally for the first time?';

UPDATE trivia_questions
SET option_a = 'about 15-20%',
    option_b = 'about 25-30%',
    option_c = 'about 35-40%',
    option_d = 'about 45-50%',
    correct_answer = 'a',
    fun_fact = 'Huge overseas, but the home market still does most of the lifting.'
WHERE company_id = 'wmt'
  AND question = 'What percentage of the company''s total revenue comes from international operations?';

UPDATE trivia_questions
SET question = 'The company is often ranked as what by annual revenue?',
    option_a = 'largest retailer',
    option_b = 'largest airline',
    option_c = 'largest bank',
    option_d = 'largest automaker',
    correct_answer = 'a',
    fun_fact = 'Scale is the whole plot. The numbers are enormous.'
WHERE company_id = 'wmt'
  AND question = 'In which year did the company become the largest retailer by revenue globally?';

UPDATE trivia_questions
SET fun_fact = COALESCE(fun_fact, 'Retail trivia at supercenter scale.')
WHERE company_id = 'wmt'
  AND fun_fact IS NULL;

-- ---------------------------------------------------------------------------
-- DIS: Walt Disney
-- ---------------------------------------------------------------------------

UPDATE trivia_questions
SET question = 'What is the company''s flagship streaming service?',
    option_a = 'hulu',
    option_b = 'disney+',
    option_c = 'espn+',
    option_d = 'abc app',
    correct_answer = 'b',
    fun_fact = 'The plus sign became an earnings-call character.'
WHERE company_id = 'dis'
  AND question = 'What was the company''s approximate annual revenue in 2022?';

UPDATE trivia_questions
SET option_a = 'sports broadcasting',
    option_b = 'animation and motion pictures',
    option_c = 'theme parks',
    option_d = 'cruise vacations',
    correct_answer = 'b',
    fun_fact = 'Before the parks, the stories came first.'
WHERE company_id = 'dis'
  AND question = 'What was the primary business segment before major theme park expansion?';

UPDATE trivia_questions
SET option_a = '1995',
    option_b = '1996',
    option_c = '1997',
    option_d = '1999',
    correct_answer = 'a',
    fun_fact = 'Broadcast TV joined the castle era.'
WHERE company_id = 'dis'
  AND question = 'In what year did the company acquire ABC Television?';

UPDATE trivia_questions
SET fun_fact = COALESCE(fun_fact, 'Entertainment trivia: the portfolio is the ride.')
WHERE company_id = 'dis'
  AND fun_fact IS NULL;

-- ---------------------------------------------------------------------------
-- HD: Home Depot
-- Included because the merged generated rows also have missing fun_facts and bad facts.
-- ---------------------------------------------------------------------------

UPDATE trivia_questions
SET option_a = '1978',
    option_b = '1972',
    option_c = '1981',
    option_d = '1975',
    correct_answer = 'a',
    fun_fact = 'Orange aprons started late in the seventies.'
WHERE company_id = 'hd'
  AND question = 'In what year was the company founded?';

UPDATE trivia_questions
SET option_a = '$130 billion',
    option_b = '$151 billion',
    option_c = '$157 billion',
    option_d = '$195 billion',
    correct_answer = 'c',
    fun_fact = 'That is a lot of lumber, paint, tools, and weekend projects.'
WHERE company_id = 'hd'
  AND question = 'What was the company''s total annual revenue in fiscal year 2022?';

UPDATE trivia_questions
SET question = 'How many countries does the company operate stores in?',
    option_a = '3',
    option_b = '8',
    option_c = '18',
    option_d = '31',
    correct_answer = 'a',
    fun_fact = 'Big footprint, but not a globe-spanning store count.'
WHERE company_id = 'hd'
  AND question = 'How many countries does the company currently operate in?';

UPDATE trivia_questions
SET fun_fact = COALESCE(fun_fact, 'Home improvement trivia. Measure twice, answer once.')
WHERE company_id = 'hd'
  AND fun_fact IS NULL;

-- ---------------------------------------------------------------------------
-- TRV: Travelers full replacement
-- ---------------------------------------------------------------------------

UPDATE trivia_questions
SET question = 'The company is primarily what type of insurer?',
    option_a = 'life insurer',
    option_b = 'health insurer',
    option_c = 'property and casualty insurer',
    option_d = 'mortgage insurer',
    correct_answer = 'c',
    fun_fact = 'This is the claims-and-premiums lane. No store racks involved.'
WHERE company_id = 'trv'
  AND question = 'In what year was the company founded?';

UPDATE trivia_questions
SET question = 'Which is one of the company''s main business segments?',
    option_a = 'business insurance',
    option_b = 'investment banking',
    option_c = 'home improvement retail',
    option_d = 'aircraft leasing',
    correct_answer = 'a',
    fun_fact = 'Commercial policies are a core part of the playbook.'
WHERE company_id = 'trv'
  AND question = 'Approximately how many stores did the company operate globally as of 2023?';

UPDATE trivia_questions
SET question = 'What does combined ratio measure for an insurer?',
    option_a = 'premium growth only',
    option_b = 'losses and expenses versus premiums',
    option_c = 'stock price versus book value',
    option_d = 'cash divided by debt',
    correct_answer = 'b',
    fun_fact = 'In insurance, under 100 is the number everyone likes to hear.'
WHERE company_id = 'trv'
  AND question = 'What was the company''s approximate annual revenue in fiscal year 2022?';

UPDATE trivia_questions
SET question = 'What do net written premiums measure?',
    option_a = 'new policies before cancellations',
    option_b = 'investment gains',
    option_c = 'premiums retained after reinsurance',
    option_d = 'claims paid in cash',
    correct_answer = 'c',
    fun_fact = 'It is premium volume with the insurance accounting dialed in.'
WHERE company_id = 'trv'
  AND question = 'In what year did the company transition from public to private ownership?';

UPDATE trivia_questions
SET question = 'Which segment covers surety and management liability products?',
    option_a = 'personal insurance',
    option_b = 'bond and specialty insurance',
    option_c = 'consumer banking',
    option_d = 'merchant services',
    correct_answer = 'b',
    fun_fact = 'Specialty insurance: less household name, very earnings-call relevant.'
WHERE company_id = 'trv'
  AND question = 'How many major brand banners does the company operate under its portfolio?';

UPDATE trivia_questions
SET question = 'Which personal lines are central to the company?',
    option_a = 'auto and homeowners',
    option_b = 'life and annuities',
    option_c = 'dental and vision',
    option_d = 'travel booking',
    correct_answer = 'a',
    fun_fact = 'Personal insurance means cars, homes, and plenty of weather talk.'
WHERE company_id = 'trv'
  AND question = 'In approximately what year did the company first launch e-commerce operations?';

UPDATE trivia_questions
SET question = 'What do catastrophe losses usually refer to?',
    option_a = 'currency swings',
    option_b = 'interest expense',
    option_c = 'brand marketing',
    option_d = 'major storms and disasters',
    correct_answer = 'd',
    fun_fact = 'When the weather gets loud, insurers talk cat losses.'
WHERE company_id = 'trv'
  AND question = 'Which of these acquisitions did the company NOT make in the 2010s?';

UPDATE trivia_questions
SET question = 'What is the company''s stock ticker?',
    option_a = 'trv',
    option_b = 'tvl',
    option_c = 'ins',
    option_d = 'pnc',
    correct_answer = 'a',
    fun_fact = 'Three letters. Umbrella-adjacent, if you squint.'
WHERE company_id = 'trv'
  AND question = 'In what year did the company exceed $1 billion in annual revenue?';

UPDATE trivia_questions
SET question = 'The company is a component of which index?',
    option_a = 'the s&p smallcap 600',
    option_b = 'the dow 30',
    option_c = 'the russell microcap',
    option_d = 'no major index',
    correct_answer = 'b',
    fun_fact = 'Insurance can be a blue-chip business too.'
WHERE company_id = 'trv'
  AND question = 'What strategic shift did the company announce regarding its store portfolio in 2019?';

UPDATE trivia_questions
SET question = 'Which cyber product area does the company discuss?',
    option_a = 'cyberrisk coverage',
    option_b = 'video streaming',
    option_c = 'grocery delivery',
    option_d = 'airline loyalty',
    correct_answer = 'a',
    fun_fact = 'Modern risk has a login screen.'
WHERE company_id = 'trv'
  AND question = 'Which corporate initiative has the company emphasized most heavily since 2020?';

UPDATE trivia_questions
SET question = 'Order of magnitude, how many people does the company employ?',
    option_a = 'about 3 thousand',
    option_b = 'about 30 thousand',
    option_c = 'about 300 thousand',
    option_d = 'about 3 million',
    correct_answer = 'b',
    fun_fact = 'Insurance is people-heavy. Underwriting does not automate itself overnight.'
WHERE company_id = 'trv'
  AND question = 'Approximately what margin improvement did the company target through efficiency initiatives?';

-- ---------------------------------------------------------------------------
-- VZ: Verizon inserts
-- ---------------------------------------------------------------------------

INSERT INTO trivia_questions
  (company_id, question, option_a, option_b, option_c, option_d,
   correct_answer, category, difficulty, is_active, fun_fact)
VALUES
  ('vz', 'The company is primarily in which business?', 'wireless and wireline telecom', 'regional banking', 'home improvement retail', 'aircraft manufacturing', 'a', 'earnings', 'easy', true, 'It is a network story first. Towers, fiber, and monthly bills.'),
  ('vz', 'What is the company''s stock ticker?', 'vzn', 'vzw', 'vz', 'vrz', 'c', 'earnings', 'easy', true, 'Short ticker. Big phone bill energy.'),
  ('vz', 'Which is one of the company''s main segments?', 'consumer', 'investment banking', 'theme parks', 'paint stores', 'a', 'earnings', 'medium', true, 'Consumer is the plan everyone with a phone can feel.'),
  ('vz', 'Which is another major segment?', 'streaming studios', 'business', 'industrial coatings', 'commercial aircraft', 'b', 'earnings', 'medium', true, 'Enterprise customers need networks too.'),
  ('vz', 'The company is a component of which index?', 'the russell 2000', 'the nasdaq biotech index', 'the dow 30', 'no major index', 'c', 'earnings', 'medium', true, 'Telecom can be old-school blue chip.'),
  ('vz', 'Which network investment comes up often on calls?', '5g', 'solar farms', 'cruise ships', 'movie theaters', 'a', 'earnings', 'easy', true, 'Every telecom call eventually finds the 5g lane.'),
  ('vz', 'Which company is a major wireless competitor?', 'at&t', 'sherwin-williams', 'boeing', 'merck', 'a', 'earnings', 'easy', true, 'The wireless scoreboard has familiar rivals.'),
  ('vz', 'Which is another major wireless competitor?', 'caterpillar', 't-mobile', 'travelers', '3m', 'b', 'earnings', 'easy', true, 'If the topic is subscribers, this name is nearby.'),
  ('vz', 'Where is the company headquartered?', 'atlanta', 'chicago', 'new york', 'dallas', 'c', 'earnings', 'medium', true, 'The headquarters answer has major-market energy.'),
  ('vz', 'What did the company divest to refocus on telecom?', 'media assets', 'mining assets', 'paint stores', 'drug brands', 'a', 'earnings', 'medium', true, 'The plot moved back to networks.'),
  ('vz', 'Order of magnitude, how many people does it employ?', 'about 10 thousand', 'about 100 thousand', 'about 1 million', 'about 10 million', 'b', 'earnings', 'medium', true, 'Running networks takes a lot of humans behind the signal bars.'),
  ('vz', 'Order of magnitude, what is annual revenue?', 'about $13 billion', 'about $130 billion', 'about $1.3 trillion', 'about $3 billion', 'b', 'earnings', 'medium', true, 'Telecom scale shows up in very large recurring revenue.');

