#!/usr/bin/env node

import Anthropic from "@anthropic-ai/sdk";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PENDING_DIR = join(__dirname, "pending");
const COMPANIES_FILE = join(__dirname, "companies.json");

const COST_LIMIT = 8.0;
const MODEL = "claude-haiku-4-5-20251001";
const INPUT_COST_PER_TOKEN = 0.8 / 1_000_000;
const OUTPUT_COST_PER_TOKEN = 4.0 / 1_000_000;

// ── Extraction prompt ───────────────────────────────────────────
const SYSTEM_PROMPT = `You are a content analyst for an earnings call bingo game called "There It Is." You extract structured game data from earnings call transcripts.

Critical rules:
- Every phrase must be 25 characters or fewer (strict — count carefully)
- No individual person names anywhere — use role references like "the CEO" if needed
- CEO Mode only — focus on executive catchphrases, corporate buzzwords, recurring verbal tics, and distinctive speaking patterns
- Title Case every phrase
- Phrases should be fun, recognizable things the audience would react to hearing on the call
- When given multiple transcripts, prioritize phrases that recur across calls — those are hot tier`;

function buildUserPrompt(companyName, quarterCount) {
  const multi = quarterCount > 1
    ? `You have ${quarterCount} quarterly transcripts. Phrases appearing in multiple calls are strong hot-tier candidates. Phrases appearing only once are warm or cold tier.`
    : `You have one transcript.`;

  return `Analyze these earnings call transcripts for ${companyName} and extract game content.

${multi}

Return ONLY valid JSON with this exact structure:

{
  "phrases": [
    {
      "phrase": "Example Phrase",
      "tier": "hot",
      "ceo_mode": true,
      "special_square": null
    }
  ],
  "badges": [
    {
      "id": "snake_case_id",
      "name": "Display Name",
      "emoji": "🎯",
      "desc": "Short description of how to earn it",
      "trigger_phrase": "Exact Phrase Match"
    }
  ],
  "trivia": [
    {
      "question": "What metric did the company highlight?",
      "option_a": "RevPAR",
      "option_b": "ADR",
      "option_c": "Occupancy",
      "option_d": "EBITDA",
      "correct_answer": "a",
      "category": "financial",
      "difficulty": "medium",
      "fun_fact": "Brief interesting context about the answer"
    }
  ]
}

PHRASES — extract at least 45 total:
- 25+ hot tier (said multiple times or across multiple calls — 50 points)
- 15+ warm tier (said at least once, likely to recur — 75 points)
- 5+ cold tier (rare/unusual, surprising if heard again — 150 points)
- Mark special_square as "great_question" for any Q&A transition phrase
- Mark special_square as "dont_overcook" for any cautionary/tempering phrase
- Mark special_square as "filibuster" for any long-winded rambling indicator
- All other phrases: special_square = null
- EVERY phrase must be ≤ 25 characters — count before including

BADGES — suggest 3-5 company-specific badges:
- Each must reference a trigger_phrase that appears in your phrases list
- Think: what phrase would be exciting/funny/rare enough to earn a badge?
- The trigger_phrase must match exactly one of your extracted phrases

TRIVIA — generate 20 questions:
- Mix of easy (5), medium (10), hard (5)
- Categories: financial, strategy, operations, culture, general
- Fun facts should add context a casual listener might not know
- No individual names in questions or answers

Return ONLY the JSON object, no markdown fences, no explanation.`;
}

// ── Helpers ──────────────────────────────────────────────────────
function esc(str) {
  return str.replace(/'/g, "''");
}

const TIER_POINTS = { hot: 50, warm: 75, cold: 150 };

function generateSQL(companyId, companyName, emoji, data) {
  const lines = [];
  lines.push(`-- Generated by ingest.js on ${new Date().toISOString()}`);
  lines.push(`-- Company: ${companyName}`);
  lines.push("");

  lines.push(
    `INSERT INTO companies (id, name, emoji, is_active, phrase_count)`,
  );
  lines.push(
    `VALUES ('${esc(companyId)}', '${esc(companyName)}', '${esc(emoji)}', true, ${data.phrases.length})`,
  );
  lines.push(
    `ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, emoji = EXCLUDED.emoji, phrase_count = EXCLUDED.phrase_count;`,
  );
  lines.push("");

  lines.push("-- Phrases");
  for (const p of data.phrases) {
    const points = TIER_POINTS[p.tier] || 50;
    const special = p.special_square ? "true" : "false";
    lines.push(
      `INSERT INTO phrases (company_id, phrase, tier, points, ceo_mode, special_square, is_active)` +
        ` VALUES ('${esc(companyId)}', '${esc(p.phrase)}', '${esc(p.tier)}', ${points}, true, ${special}, true);`,
    );
  }
  lines.push("");

  lines.push("-- Trivia questions");
  for (const t of data.trivia) {
    lines.push(
      `INSERT INTO trivia_questions (company_id, question, option_a, option_b, option_c, option_d, correct_answer, category, difficulty, fun_fact, is_active)` +
        ` VALUES ('${esc(companyId)}', '${esc(t.question)}', '${esc(t.option_a)}', '${esc(t.option_b)}', '${esc(t.option_c)}', '${esc(t.option_d)}', '${esc(t.correct_answer)}', '${esc(t.category)}', '${esc(t.difficulty)}', '${esc(t.fun_fact)}', true);`,
    );
  }
  lines.push("");

  if (data.badges && data.badges.length > 0) {
    lines.push("-- Recommended badge mappings (add to src/lib/badges.js)");
    for (const b of data.badges) {
      lines.push(
        `-- ${b.id}: ${b.emoji} "${b.name}" — ${b.desc} (trigger: "${b.trigger_phrase}")`,
      );
    }
    lines.push("");
  }

  return lines.join("\n");
}

function validatePhrases(phrases) {
  const warnings = [];
  for (const p of phrases) {
    if (p.phrase.length > 25) {
      warnings.push(`  ⚠ OVER 25 CHARS (${p.phrase.length}): "${p.phrase}"`);
    }
  }
  const hot = phrases.filter((p) => p.tier === "hot").length;
  const warm = phrases.filter((p) => p.tier === "warm").length;
  const cold = phrases.filter((p) => p.tier === "cold").length;
  if (hot < 20) warnings.push(`  ⚠ Only ${hot} hot phrases (wanted 25+)`);
  if (warm < 10) warnings.push(`  ⚠ Only ${warm} warm phrases (wanted 15+)`);
  if (cold < 3) warnings.push(`  ⚠ Only ${cold} cold phrases (wanted 5+)`);
  return warnings;
}

// ── Main ────────────────────────────────────────────────────────
async function main() {
  if (!process.env.ANTHROPIC_API_KEY) {
    console.error("ANTHROPIC_API_KEY not set in environment.");
    process.exit(1);
  }

  if (!existsSync(COMPANIES_FILE)) {
    console.error(`Companies file not found: ${COMPANIES_FILE}`);
    process.exit(1);
  }

  const companies = JSON.parse(readFileSync(COMPANIES_FILE, "utf-8"));
  const active = companies.filter(
    (c) => c.transcripts && c.transcripts.length > 0,
  );

  if (active.length === 0) {
    console.error(
      "No companies have transcripts listed. Edit scripts/companies.json.",
    );
    process.exit(1);
  }

  const client = new Anthropic();

  if (!existsSync(PENDING_DIR)) {
    mkdirSync(PENDING_DIR, { recursive: true });
  }

  const totalTranscripts = active.reduce(
    (sum, c) => sum + c.transcripts.length,
    0,
  );
  console.log(`\n  There It Is — Transcript Ingestion`);
  console.log(`  Model: ${MODEL}`);
  console.log(`  Budget: $${COST_LIMIT.toFixed(2)}`);
  console.log(
    `  Companies: ${active.length} (${totalTranscripts} total transcripts)\n`,
  );

  let totalCost = 0;
  let processed = 0;
  let failed = 0;

  for (const company of active) {
    if (totalCost >= COST_LIMIT) {
      console.log(
        `\n  BUDGET LIMIT ($${COST_LIMIT.toFixed(2)}) reached. Stopping.`,
      );
      break;
    }

    console.log(
      `  [${processed + failed + 1}/${active.length}] ${company.name} (${company.ticker})`,
    );
    console.log(
      `  Fetching ${company.transcripts.length} transcripts...`,
    );

    const docBlocks = [];
    let totalBytes = 0;
    let fetchFailed = false;

    for (const t of company.transcripts) {
      try {
        const resp = await fetch(t.url);
        if (!resp.ok) {
          throw new Error(`HTTP ${resp.status} for ${t.quarter}`);
        }
        const buf = Buffer.from(await resp.arrayBuffer());
        totalBytes += buf.length;
        docBlocks.push({
          type: "document",
          source: {
            type: "base64",
            media_type: "application/pdf",
            data: buf.toString("base64"),
          },
        });
        process.stdout.write(`  ✓ ${t.quarter} (${(buf.length / 1_048_576).toFixed(1)} MB)\n`);
      } catch (err) {
        console.error(`  ✗ ${t.quarter}: ${err.message}`);
      }
    }

    if (docBlocks.length === 0) {
      console.error(`  ✗ No transcripts fetched successfully. Skipping.\n`);
      failed++;
      continue;
    }

    const sizeMB = (totalBytes / 1_048_576).toFixed(1);
    console.log(
      `  ${docBlocks.length}/${company.transcripts.length} fetched (${sizeMB} MB total)`,
    );
    console.log(`  Calling ${MODEL}...`);

    let response;
    try {
      response = await client.messages.create({
        model: MODEL,
        max_tokens: 8192,
        system: SYSTEM_PROMPT,
        messages: [
          {
            role: "user",
            content: [
              ...docBlocks,
              {
                type: "text",
                text: buildUserPrompt(company.name, docBlocks.length),
              },
            ],
          },
        ],
      });
    } catch (err) {
      console.error(`  ✗ API call failed: ${err.message}`);
      failed++;
      continue;
    }

    const inputTokens = response.usage.input_tokens;
    const outputTokens = response.usage.output_tokens;
    const callCost =
      inputTokens * INPUT_COST_PER_TOKEN +
      outputTokens * OUTPUT_COST_PER_TOKEN;
    totalCost += callCost;

    console.log(
      `  Tokens: ${inputTokens.toLocaleString()} in / ${outputTokens.toLocaleString()} out`,
    );
    console.log(
      `  Cost: $${callCost.toFixed(4)} this call | $${totalCost.toFixed(4)} running total`,
    );

    const raw = response.content[0].text;
    let data;
    try {
      const cleaned = raw.replace(/^```json?\s*/i, "").replace(/```\s*$/, "");
      data = JSON.parse(cleaned);
    } catch (err) {
      console.error(`  ✗ Failed to parse JSON response: ${err.message}`);
      const debugPath = join(PENDING_DIR, `${company.id}_raw.txt`);
      writeFileSync(debugPath, raw);
      console.error(`  Raw response saved to ${debugPath}`);
      failed++;
      continue;
    }

    if (!data.phrases || !data.trivia) {
      console.error(`  ✗ Response missing required fields (phrases/trivia)`);
      failed++;
      continue;
    }

    const overLength = data.phrases.filter((p) => p.phrase.length > 25);
    if (overLength.length > 0) {
      console.log(
        `  Trimming ${overLength.length} phrases over 25 chars...`,
      );
      data.phrases = data.phrases.filter((p) => p.phrase.length <= 25);
    }

    const warnings = validatePhrases(data.phrases);
    if (warnings.length > 0) {
      console.log(`  Warnings:`);
      warnings.forEach((w) => console.log(w));
    }

    const sql = generateSQL(company.id, company.name, company.emoji, data);
    const outPath = join(PENDING_DIR, `${company.id}.sql`);
    writeFileSync(outPath, sql);

    console.log(
      `  ✓ ${data.phrases.length} phrases, ${data.trivia.length} trivia, ${(data.badges || []).length} badges`,
    );
    console.log(`  → ${outPath}\n`);
    processed++;
  }

  console.log(`  ─────────────────────────────────`);
  console.log(`  Done. ${processed} succeeded, ${failed} failed.`);
  console.log(`  Total API cost: $${totalCost.toFixed(4)}`);
  console.log(`  SQL files in: ${PENDING_DIR}\n`);
}

main().catch((err) => {
  console.error(`Fatal: ${err.message}`);
  process.exit(1);
});
