-- Seed Hilton phrases from hardcoded src/lib/phrases.js.
-- Executed via Supabase MCP on 2026-05-28.
-- Source of truth: phrases.js HOT/WARM/COLD arrays (51 total).
-- All phrases verified <= 25 chars. 0 rejected by DB constraint.

INSERT INTO phrases (company_id, phrase, tier, points, ceo_mode, special_square, is_active) VALUES
-- HOT tier (50 points)
('hilton', 'Serial Compounder',       'hot', 50, true,  null,             true),
('hilton', 'Brand-Led',               'hot', 50, true,  null,             true),
('hilton', 'Network-Driven',          'hot', 50, true,  null,             true),
('hilton', 'Platform-Enabled',        'hot', 50, true,  null,             true),
('hilton', 'Flywheel',                'hot', 50, true,  null,             true),
('hilton', 'Filibuster',              'hot', 50, true,  'filibuster',     true),
('hilton', 'Never Say Never',         'hot', 50, true,  null,             true),
('hilton', 'Long Long Time',          'hot', 50, true,  null,             true),
('hilton', 'Early Days',              'hot', 50, true,  null,             true),
('hilton', 'Network Effect',          'hot', 50, true,  null,             true),
('hilton', 'White Space',             'hot', 50, true,  null,             true),
('hilton', 'Shots on Goal',           'hot', 50, true,  null,             true),
('hilton', 'I''d Take The Over',      'hot', 50, true,  null,             true),
('hilton', 'Green Shoots',            'hot', 50, true,  null,             true),
('hilton', 'C-Shaped Economy',        'hot', 50, false, null,             true),
('hilton', 'Don''t Overcook It',      'hot', 50, true,  'dont_overcook',  true),
('hilton', 'Above Algorithm',         'hot', 50, false, null,             true),
('hilton', 'Commercial Engine',       'hot', 50, false, null,             true),
('hilton', 'Conversion Rate',         'hot', 50, false, null,             true),
('hilton', 'Great Question',          'hot', 50, false, 'great_question', true),
('hilton', 'Sneak One More In',       'hot', 50, false, null,             true),
('hilton', 'Unpack That',             'hot', 50, false, null,             true),
('hilton', 'Flow Through',            'hot', 50, false, null,             true),
('hilton', 'Rule Of Thumb',           'hot', 50, false, null,             true),
('hilton', 'In-Year For-Year',        'hot', 50, false, null,             true),
('hilton', 'Return Capital',          'hot', 50, false, null,             true),
('hilton', 'Asset-Light',             'hot', 50, false, null,             true),
('hilton', 'Chain Scales',            'hot', 50, false, null,             true),
-- WARM tier (75 points)
('hilton', 'War Is War',              'warm', 75, true,  null, true),
('hilton', 'K Economy',               'warm', 75, false, null, true),
('hilton', 'AI Complex',              'warm', 75, false, null, true),
('hilton', 'Productivity Boom',       'warm', 75, false, null, true),
('hilton', 'Middle Class',            'warm', 75, false, null, true),
('hilton', 'Macro Tailwinds',         'warm', 75, false, null, true),
('hilton', 'APAC Ex China',           'warm', 75, false, null, true),
('hilton', 'Business Transient',      'warm', 75, false, null, true),
('hilton', 'Leisure Transient',       'warm', 75, false, null, true),
('hilton', 'Group Leading',           'warm', 75, false, null, true),
('hilton', 'Development Outlook',     'warm', 75, false, null, true),
('hilton', 'Organic Growth',          'warm', 75, false, null, true),
('hilton', 'Tech Stack',              'warm', 75, false, null, true),
('hilton', 'Deregulation',            'warm', 75, false, null, true),
('hilton', 'Margin Expansion',        'warm', 75, false, null, true),
('hilton', 'Fee Growth',              'warm', 75, false, null, true),
('hilton', 'Loyalty Mix',             'warm', 75, false, null, true),
('hilton', 'Owned And Leased',        'warm', 75, false, null, true),
-- COLD tier (150 points)
('hilton', 'Gonculator',              'cold', 150, false, null, true),
('hilton', 'Unforeseen Circumstances','cold', 150, false, null, true),
('hilton', 'I''ve Been Consistent',   'cold', 150, true,  null, true),
('hilton', 'Serial Acquirer',         'cold', 150, false, null, true),
('hilton', 'Psychic',                 'cold', 150, false, null, true);
